### ISSUE TITLE
Not migrated from the original

### ISSUE THREAD

**Issue by vivekvkk** [SoftwareEngineeringToolDemos/ICSE-2012-ConcernReCS#6]
The repo was not migrated from the original and hence missing the history.

**Comment by pulkeshyadav** [comment]
Could not find the code on any repository to migrate it from, so just uploaded the code.

**Comment by pulkeshyadav** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-ConcernReCS#5
